Project setup
Harshtroo/tms pull request #1
Opened 2023-08-22 07:29 UTC by Harshtroo

2023-08-22 09:46 UTC, yatishTT requested changes

2023-08-22 09:46 UTC, yatishTT commented on .gitignore
> +build/
why unwanted expressions are there

2023-08-22 09:46 UTC, yatishTT commented on requirements/base.txt
> +elastic-apm==6.13.2
un wanted requiremnts

2023-08-22 09:46 UTC, yatishTT commented on tms/tms/settings/production.py
> +from sentry_sdk.integrations.django import DjangoIntegration
where you are using sentry ?

2023-08-22 09:46 UTC, yatishTT commented on tms/tms/settings/production.py
> +# https://docs.djangoproject.com/en/dev/ref/settings/#session-cookie-secure
unnecessary settings

2023-08-22 12:15 UTC, yatishTrootech requested changes

2023-08-22 12:15 UTC, yatishTrootech commented on .gitignore
> +tms/utils
why utils ?

2023-08-22 12:20 UTC, Harshtroo commented on .gitignore
> +tms/utils
because right now utils not use so

2023-08-24 05:01 UTC, yatishTT requested changes

2023-08-24 05:01 UTC, yatishTT commented on .gitignore
> +db/
only expression related to your project should be in this file

2023-08-24 07:48 UTC, yatishTrootech requested changes

2023-08-24 07:48 UTC, yatishTrootech commented on .gitignore
> +.idea/
*.py[cod]
__pycache__/
.idea/
tmp/*
*.log.*
*.log
tms/media/*
.idea/*
tms/conftest.py
tms/tms.db

2023-08-24 11:23 UTC, merged