Feature/frontend register
Harshtroo/tms pull request #6
Opened 2023-09-06 11:27 UTC by Harshtroo

2023-09-06 11:57 UTC, Dhruvi-Makwana commented on tms/static/js/register.js
>                          if (response.status === "success") {
remove debugger

2023-09-06 12:00 UTC, Dhruvi-Makwana commented on tms/static/js/register.js
> +                            showMessage("Error: " + response.message, "red");
why triple ==== you can user ==

2023-09-11 06:37 UTC, yatishTrootech requested changes

2023-09-11 06:37 UTC, yatishTrootech commented on tms/static/js/base.js
> +var baseURL = "http://127.0.0.1:8000"
it should not be full url

2023-09-11 06:37 UTC, yatishTrootech commented on tms/static/js/register.js
> +var registerURL = baseURL + '/register/'
no need of base url

2023-09-11 06:37 UTC, yatishTrootech commented on tms/static/js/register.js
> +        $("#message-container").html(messageElement);
it should be in base

2023-09-11 06:37 UTC, yatishTrootech commented on tms/tms/settings/base.py
> +    "django_summernote",
add ss/videos from of you functionality

2023-09-11 11:18 UTC, Harshtroo commented
[register.webm](https://github.com/Harshtroo/tms/assets/123172610/4da1740a-afd3-4984-bd74-1737d2d18241)

2023-09-12 03:46 UTC, yatishTT approved these changes

2023-09-12 04:35 UTC, merged