done login UI
Harshtroo/tms pull request #7
Opened 2023-09-12 10:52 UTC by Harshtroo

2023-09-12 10:55 UTC, yatishTrootech requested changes

2023-09-12 10:55 UTC, yatishTrootech commented on tms/clickup/urls.py
> +    path("get_register/", views.get_register_page, name="get_register"),
register

2023-09-12 10:55 UTC, yatishTrootech commented on tms/clickup/urls.py
> +    path("login_page/", views.get_login_page, name="login_page"),
login

2023-09-12 10:55 UTC, yatishTrootech commented on tms/clickup/views.py
> +def get_login_page(request):
login

2023-09-12 10:55 UTC, yatishTrootech commented on tms/clickup/views.py
> +        return JsonResponse({"data": serializer.data, "status": "success", "success_message": "Register successfully"},
return Response

2023-09-12 11:04 UTC, Dhruvi-Makwana commented on tms/clickup/views.py
> +                             "success_message": "Successfully logged in."}, status=status.HTTP_200_OK)
add message in constant.

2023-09-13 06:16 UTC, yatishTrootech approved these changes

2023-09-13 06:19 UTC, merged